# Generated by Django 5.0.6 on 2024-06-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemapi', '0002_remove_item_suppliers'),
        ('supplierapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='items',
            field=models.ManyToManyField(related_name='items', to='itemapi.item'),
        ),
    ]
