# Generated by Django 5.0.6 on 2024-06-14 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplierapi', '0002_supplier_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='items',
        ),
    ]
