# Generated by Django 5.0.6 on 2024-06-14 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='suppliers',
        ),
    ]
